### ISSUE TITLE
What's License of Airlift.xml?

### ISSUE THREAD

**Issue by k0kubun** [airlift/codestyle#6]
I want to include IntelliJIdea14/Airlift.xml in another repository. What's the License of that file? The same as [airlift/airlift](https://github.com/airlift/airlift/blob/master/LICENSE)?

[edit] I decided to use this repository as git submodule for now.

**Comment by electrum** [comment]
This is a config file exported from IntelliJ. There's no copyright or license. You are free to copy it at will. If you configure your IDE the same way and perform an export, you will end up with the same file.


![screen shot 2017-08-30 at 7 58 43 am](https://user-images.githubusercontent.com/9230/29879216-4b9453f2-8d59-11e7-932d-c139735b524c.png)
